name: BUILD AND DEPLOY CODE

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    job1:
        run-on: ubuntu-latest
        steps:
            - name: Install dependencies
            - uses: actions/checkout@v2
            - name: Say hi to Rellika
              run: Echo "Hi Rellika"
